version: "3.9"

services:
  jekyll:
    build: .
    working_dir: /site
    environment:
      JEKYLL_ENV: development
    command: bash -lc "bundle install && bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./docs:/site
      - bundle_cache:/usr/local/bundle
volumes:
  bundle_cache:
