title: "Repitito"
tagline: "The Little Key Repeater"
description: "Capture keyboard input once and replay it any time."
url: "https://mabino.github.io/repitito"
repository: "mabino/repitito"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: true
nav:
  - text: "Home"
    url: /
  - text: "Getting Started"
    url: /#getting-started
  - text: "Features"
    url: /#features
